package com.CrudExample.CRUD.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="Product_TBL")
public class Product
{
    @Id//Id le annotate gareko instance variables nai primary key huncha
    @GeneratedValue//Yo annotation le garda value of id autogenerated huncha database ma
    private int id;//Id le annotate gareko le garda int id mero primary key ho
    private String name;
    private int quantity;
    private double price;


}
